# Generated by Django 3.1.8 on 2021-11-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_eventpage_discord_event_link"),
        ("events", "0018_auto_20211016_1852"),
    ]

    operations = []
