# Generated by Django 3.0.8 on 2020-07-12 15:25

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    replaces = [('newsletter', '0001_initial'), ('newsletter', '0002_mail_date_created'), ('newsletter', '0003_auto_20161008_1726'), ('newsletter', '0004_auto_20161009_2022'), ('newsletter', '0005_auto_20161009_2029'), ('newsletter', '0006_subscription_unsubscribe_token'), ('newsletter', '0007_auto_20171016_1330')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_subscribed', models.DateTimeField(default=django.utils.timezone.now)),
                ('unsubscribe_token', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('text', markdownx.models.MarkdownxField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender_email', models.EmailField(default='newsletter@uwcs.co.uk', max_length=254)),
                ('sender_name', models.CharField(default='UWCS Newsletter', max_length=50)),
            ],
        ),
    ]
