# Generated by Django 3.0.8 on 2020-07-20 18:09

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20200720_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="alert",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
