# Generated by Django 3.0.8 on 2020-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_homepage_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="alert_link",
            field=models.URLField(blank=True),
        ),
    ]
