name: CI Checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Qodana scan"
        uses: JetBrains/qodana-action@v4.1.0
        with:
          linter: jetbrains/qodana-python

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
            python-version: 3.9
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Check formatting with black
        run: |
            black --check .

