name: Qodana

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: JetBrains/qodana-action@v3.2.1
        with:
          linter: qodana-jvm-community
          fail-threshold: 10
          additional-env-variables: |
              IDEA_PROPERTIES='/data/project/idea.properties'
