name: Qodana

on:
  push:
  pull_request:    
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Qodana scan"
        uses: JetBrains/qodana-action@v4.1.0
        with:
          linter: jetbrains/qodana-python
